# Generated by Django 4.0.3 on 2022-03-24 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='rg',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
